print('{:=^50}'.format('Numeros'))
n1 = input('Digite um numero entre 0 e 9999:')
print('Unidade:{}'.format(n1[3]))
print('Dezena:{}'.format(n1[2]))
print('Centena:{}'.format(n1[1]))
print('Milhar:{}'.format(n1[0]))